/*
 * App.java
 *
 * Created on 21 Март 2005 г., 8:40
 */

package j5feldman.boo;
import java.io.*;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author  Jacob Feldman
 */
public class App extends javax.swing.JFrame {
    
    /** Creates new form App */
    public App() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        stopButton = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jFileMenu = new javax.swing.JMenu();
        goItem = new javax.swing.JMenuItem();
        configItem = new javax.swing.JMenuItem();
        readIten = new javax.swing.JMenuItem();

        getContentPane().setLayout(new java.awt.GridLayout(5, 1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jLabel5.setText("\u0434\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u043e \u043e\u0431\u044a\u0435\u043a\u0442\u043e\u0432");
        jPanel1.add(jLabel5);

        jLabel1.setText("0");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1);

        jLabel6.setText("\u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0435\u0435 \u0432\u0440\u0435\u043c\u044f \u043d\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u0435");
        jPanel2.add(jLabel6);

        jLabel2.setText("0");
        jPanel2.add(jLabel2);

        getContentPane().add(jPanel2);

        jLabel7.setText("\u043c\u0430\u043a\u0441\u0438\u043c\u0430\u043b\u044c\u043d\u043e\u0435 \u0432\u0440\u0435\u043c\u044f \u043d\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u0435");
        jPanel3.add(jLabel7);

        jLabel3.setText("0");
        jPanel3.add(jLabel3);

        getContentPane().add(jPanel3);

        jLabel8.setText("\u0441\u0440\u0435\u0434\u043d\u0435\u0435 \u0432\u0440\u0435\u043c\u044f \u043d\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u0435");
        jPanel4.add(jLabel8);

        jLabel4.setText("0");
        jPanel4.add(jLabel4);

        getContentPane().add(jPanel4);

        stopButton.setText("stop");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        getContentPane().add(stopButton);

        jFileMenu.setText("File");
        goItem.setText("Create");
        goItem.setActionCommand("go");
        goItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goItemActionPerformed(evt);
            }
        });

        jFileMenu.add(goItem);
        goItem.getAccessibleContext().setAccessibleName("go");

        configItem.setText("config");
        configItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configItemActionPerformed(evt);
            }
        });

        jFileMenu.add(configItem);

        readIten.setText("Read");
        readIten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readItenActionPerformed(evt);
            }
        });

        jFileMenu.add(readIten);

        jMenuBar2.add(jFileMenu);

        setJMenuBar(jMenuBar2);

        pack();
    }//GEN-END:initComponents
    MyThread[] threads = new MyThread[100];
    private void readItenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readItenActionPerformed
        go=true;
        for(int i=0;i<100;i++){
            threads[i]=new MyThread(this,""); 
            threads[i].start();
        }
    }//GEN-LAST:event_readItenActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        go=false;
    }//GEN-LAST:event_stopButtonActionPerformed

    private void goItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goItemActionPerformed
        go = true;
        th = new MyThread(this,null); 
        th.start();
    }//GEN-LAST:event_goItemActionPerformed
    String schemaName="";
    File confFile = null;
    MyThread th;
    private void configItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configItemActionPerformed
        schemaName = JOptionPane.showInputDialog(this,"schema name:");
        if(schemaName == null) return;
        
        JFileChooser fc = new JFileChooser("c:/feldman");
        int returnVal = fc.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
         try{
            confFile = fc.getSelectedFile();
         }catch(Exception e){}
        }  

        pack();
    }//GEN-LAST:event_configItemActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem configItem;
    private javax.swing.JMenuItem goItem;
    private javax.swing.JMenu jFileMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JMenuItem readIten;
    private javax.swing.JButton stopButton;
    // End of variables declaration//GEN-END:variables
    String getText1(){
        return jLabel1.getText();
    }
    
    String getText2(){
        return jLabel2.getText();
    }    
    
    void setText1(String t){
        jLabel1.setText(t);
    }
    void setText2(String t){
        jLabel2.setText(t);
    }
    String getText3(){
        return jLabel3.getText();
    }
    
    String getText4(){
        return jLabel4.getText();
    }    
    
    void setText3(String t){
        jLabel3.setText(t);
    }
    void setText4(String t){
        jLabel4.setText(t);
    }
    public boolean go;
}
